name: Destroy aws playground

on:
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout terraform code
        uses: actions/checkoutv@4
      
      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
        
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
      
      - name: Terraform destroy
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform destroy -auto-approve