name: Destroy aws playground

on:
  workflow_dispatch: # manual trigger
    inputs:
      target:
        description: 'Target infrastructure to be destroyed (app, network, backend)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout terraform code
        uses: actions/checkout@v4
      
      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
        
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          case ${{ github.event.inputs.target }} in
            app) cd app ;;
            network) cd network ;;
            backend) cd backend ;;
            *) echo "Invalid target: ${{ github.event.inputs.target }}"; exit 1 ;;
          esac
          terraform init
      
      - name: Terraform destroy
        if: github.event.inputs.target != ''
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          case ${{ github.event.inputs.target }} in
            app) cd app ;;
            network) cd network ;;
            backend) cd backend ;;
            *) echo "Invalid target: ${{ github.event.inputs.target }}"; exit 1 ;;
          esac          
          terraform destroy -auto-approve