name: Build aws playground

on:
  workflow_disptach: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout terraform code
        uses: actions/checkoutv@4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
        
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: {{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init
      
      - name: Terraform plan
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: {{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -auto-approve

      - name: Upload plan artifact
        uses: actions/checkoutv@4
        with:
          name: tfplan
          path: tfplan